caldera_adversary_id: 7fbc629e-5f22-4aea-95f6-c895ba66f08b
description: T1003.003 | credential-access | ESCU - Creation of Shadow Copy - Rule
display_name: SPLUNK ES / Creation of Shadow Copy / Create Volume Shadow Copy with
  WMI
name: escu_040
targets:
- role: workstation
techniques:
- caldera_ability_id: cf60378dd1bbaccd4e7391c0317da202
  id: T1003.003
  name: Create Volume Shadow Copy with WMI
  target_role: workstation
