caldera_adversary_id: 4879061c-fa33-4ae9-8c85-d1489fdf43f5
description: T1218.005 | defense-evasion | ESCU - Detect mshta inline hta execution
  - Rule
display_name: SPLUNK ES / Detect mshta inline hta execution / Mshta used to Execute
  PowerShell
name: escu_026
targets:
- role: workstation
techniques:
- caldera_ability_id: 54a7ac8fc8991511de9993983d3d3215
  id: T1218.005
  name: Mshta used to Execute PowerShell
  target_role: workstation
