caldera_adversary_id: 70acc920-9702-43fc-aca3-1ea7243aa1f4
description: T1140 | defense-evasion | ESCU - CertUtil With Decode Argument - Rule
display_name: SPLUNK ES / CertUtil With Decode Argument / Certutil Rename and Decode
name: escu_017
targets:
- role: workstation
techniques:
- caldera_ability_id: e510c5fd2f1ea418990fcf06775bc9b4
  id: T1140
  name: Certutil Rename and Decode
  target_role: workstation
