caldera_adversary_id: 32ddb8c9-f3a8-4b9a-a953-e0e837951f4d
description: T1059.003 | execution | ESCU - CMD Carry Out String Command Parameter
  - Rule
display_name: SPLUNK ES / CMD Carry Out String Command Parameter / Simulate BlackByte
  Ransomware Print Bombing
name: escu_012
targets:
- role: workstation
techniques:
- caldera_ability_id: 942d94dff3cc494bacf5517e775321a7
  id: T1059.003
  name: Simulate BlackByte Ransomware Print Bombing
  target_role: workstation
